require('dotenv').config(); 

const { PGHOST, PGDATABASE, PGUSER, PGPASSWORD,PORT ,HASH_SALT_ROUNDS,JWT_SECRET,API_KEY,AI_MODEL,
CLOUDINARY_CLOUD_NAME,CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET} = process.env;



module.exports = {
    PGHOST,
    PGDATABASE,
    PGUSER,
    PGPASSWORD,
    PORT,
    HASH_SALT_ROUNDS,
    JWT_SECRET,
    API_KEY,
    AI_MODEL,
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET
};